apiVersion: v1
kind: Service
metadata:
  name: py-app-active-svc
  namespace: NAMESPACE
  labels:
    app: py-app-active
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 5000
  selector:
    app: py-app
    
---    
apiVersion: v1
kind: Service
metadata:
  name: py-app-preview-svc
  namespace: NAMESPACE
  labels:
    app: py-app-preview
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 5000
  selector:
    app: py-app
